version: '3.7'
services:

  cloudflare-companion:
    image: tiredofit/traefik-cloudflare-companion
    container_name: cloudflare-companion
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - API_KEY=1234
      - TARGET_DOMAIN=host.example.org
      - DOMAIN1=example.org
      - DOMAIN2_ZONE_ID=1234567890
    networks:
    - internal
    - services
    restart: always

networks:
  internal:
    external: false
  services:
    external: true